import mongoose from "mongoose";
import { Task } from "../routes/v1/task/task.model.js";
import { ITask } from "../routes/v1/shared/types/type.js";

const userIds = [
    "69ea1e59d3b0284821753f50",
    "69ea1e59d3b0284821753f55",
    "69ea1e59d3b0284821753f53",
    "69ea1e59d3b0284821753f51",
    "69ea1e59d3b0284821753f56",
    "69ea1e59d3b0284821753f57",
    "69ea1e59d3b0284821753f54",
    "69ea1e59d3b0284821753f59",
];

const mockTasks = [
    {
        title: "Setup Project Auth",
        description: "Implement JWT login and registration flow.",
        status: "done",
        priority: "critical",
        dueDate: new Date("2026-05-01"),
        assignees: [userIds[0]],
        reporter: userIds[1],
    },
    {
        title: "Design Landing Page",
        description: "Create high-fidelity mockups for the homepage.",
        status: "in_progress",
        priority: "high",
        dueDate: new Date("2026-05-05"),
        assignees: [userIds[1], userIds[2]],
        reporter: userIds[0],
    },
    {
        title: "Fix Navbar Bug",
        description: "Mobile menu is not closing on link click.",
        status: "todo",
        priority: "medium",
        dueDate: new Date("2026-04-25"),
        assignees: [userIds[3]],
        reporter: userIds[2],
    },
    {
        title: "Database Migration",
        description: "Migrate user profiles to the new schema.",
        status: "done",
        priority: "critical",
        dueDate: new Date("2026-04-30"),
        assignees: [userIds[4]],
        reporter: userIds[5],
    },
    {
        title: "API Documentation",
        description: "Write Swagger docs for the Task endpoints.",
        status: "in_progress",
        priority: "low",
        dueDate: new Date("2026-05-10"),
        assignees: [userIds[5]],
        reporter: userIds[4],
    },
    {
        title: "Redux Integration",
        description: "Centralize state management for user data.",
        status: "todo",
        priority: "medium",
        dueDate: new Date("2026-05-12"),
        assignees: [userIds[6], userIds[0]],
        reporter: userIds[7],
    },
    {
        title: "Deploy to Staging",
        description: "Setup CI/CD pipeline for the staging branch.",
        status: "done",
        priority: "high",
        dueDate: new Date("2026-04-20"),
        assignees: [userIds[7]],
        reporter: userIds[1],
    },
    {
        title: "Unit Testing",
        description: "Write tests for the auth middleware.",
        status: "todo",
        priority: "high",
        dueDate: new Date("2026-05-15"),
        assignees: [userIds[2]],
        reporter: userIds[3],
    },
    {
        title: "UI Components Library",
        description: "Build reusable button and input components.",
        status: "in_progress",
        priority: "medium",
        dueDate: new Date("2026-05-18"),
        assignees: [userIds[1]],
        reporter: userIds[6],
    },
    {
        title: "Email Service Setup",
        description: "Configure Nodemailer for welcome emails.",
        status: "todo",
        priority: "low",
        dueDate: new Date("2026-05-20"),
        assignees: [userIds[4]],
        reporter: userIds[0],
    },
    {
        title: "Optimize Image Assets",
        description: "Compress all SVG and PNG assets for web.",
        status: "done",
        priority: "low",
        dueDate: new Date("2026-04-22"),
        assignees: [userIds[0]],
        reporter: userIds[5],
    },
    {
        title: "SEO Audit",
        description: "Check meta tags and lighthouse score.",
        status: "todo",
        priority: "medium",
        dueDate: new Date("2026-06-01"),
        assignees: [userIds[3]],
        reporter: userIds[2],
    },
    {
        title: "Error Logging Setup",
        description: "Integrate Sentry for backend error tracking.",
        status: "in_progress",
        priority: "critical",
        dueDate: new Date("2026-05-02"),
        assignees: [userIds[5]],
        reporter: userIds[4],
    },
    {
        title: "Search Functionality",
        description: "Implement fuzzy search for task titles.",
        status: "todo",
        priority: "high",
        dueDate: new Date("2026-05-25"),
        assignees: [userIds[7], userIds[6]],
        reporter: userIds[1],
    },
    {
        title: "Footer Redesign",
        description: "Add social links and newsletter signup.",
        status: "done",
        priority: "low",
        dueDate: new Date("2026-04-28"),
        assignees: [userIds[2]],
        reporter: userIds[0],
    },
    {
        title: "Password Reset Logic",
        description: "Handle forgot password token generation.",
        status: "in_progress",
        priority: "high",
        dueDate: new Date("2026-05-08"),
        assignees: [userIds[1]],
        reporter: userIds[7],
    },
    {
        title: "Dark Mode Toggle",
        description: "Implement theme switching logic using Tailwind.",
        status: "todo",
        priority: "medium",
        dueDate: new Date("2026-05-30"),
        assignees: [userIds[4]],
        reporter: userIds[3],
    },
    {
        title: "Rate Limiting",
        description: "Add express-rate-limit to public APIs.",
        status: "done",
        priority: "critical",
        dueDate: new Date("2026-04-21"),
        assignees: [userIds[0]],
        reporter: userIds[6],
    },
    {
        title: "Profile Picture Upload",
        description: "Integrate Cloudinary for user images.",
        status: "todo",
        priority: "medium",
        dueDate: new Date("2026-06-05"),
        assignees: [userIds[5]],
        reporter: userIds[2],
    },
    {
        title: "Payment Gateway",
        description: "Initial setup for Stripe integration.",
        status: "in_progress",
        priority: "critical",
        dueDate: new Date("2026-06-10"),
        assignees: [userIds[6]],
        reporter: userIds[0],
    },
    {
        title: "Accessibility Fixes",
        description: "Fix aria-labels and keyboard navigation.",
        status: "todo",
        priority: "medium",
        dueDate: new Date("2026-05-14"),
        assignees: [userIds[3]],
        reporter: userIds[4],
    },
    {
        title: "Code Refactoring",
        description: "Clean up controllers and move logic to services.",
        status: "done",
        priority: "low",
        dueDate: new Date("2026-04-15"),
        assignees: [userIds[7]],
        reporter: userIds[1],
    },
    {
        title: "Security Headers",
        description: "Implement Helmet.js for express security.",
        status: "in_progress",
        priority: "high",
        dueDate: new Date("2026-05-04"),
        assignees: [userIds[2]],
        reporter: userIds[5],
    },
    {
        title: "Push Notifications",
        description: "Setup Firebase for task reminders.",
        status: "todo",
        priority: "medium",
        dueDate: new Date("2026-06-15"),
        assignees: [userIds[1]],
        reporter: userIds[3],
    },
    {
        title: "Beta Launch Prep",
        description: "Final check of all critical user flows.",
        status: "in_progress",
        priority: "critical",
        dueDate: new Date("2026-06-20"),
        assignees: [userIds[0], userIds[4]],
        reporter: userIds[7],
    },
];

async function seedTasks() {
    try {
        await mongoose.connect("mongodb://127.0.0.1:27017/taskmanager");
        await Task.create(mockTasks);
        console.log("✅ Seeded 25 tasks successfully!");
        process.exit(0);
    } catch (err) {
        console.error(err);
        process.exit(1);
    }
}

seedTasks();
